### ISSUE TITLE
Canifis to Brimhaven strange behavior with fairy ring

### ISSUE THREAD

**Issue by lbenedetto** [Skretzo/shortest-path#21]
![image](https://user-images.githubusercontent.com/4466272/193906886-63627ae0-5683-4f22-a5a6-0801d4db6239.png)
Fairy ring TP shoots far off past wilderness and into the black until it reaches this
![image](https://user-images.githubusercontent.com/4466272/193906979-63802dc1-0d49-4819-bda2-ab4b7c80a1e5.png)
Goes even farther up the the map until this
![image](https://user-images.githubusercontent.com/4466272/193907061-423a9cda-eac0-472c-8231-4defca653742.png)
And then comes out here
![image](https://user-images.githubusercontent.com/4466272/193907112-ccb5ff18-ca3b-470c-904e-f2f4545e8fea.png)
Actual best path is home TP to Rimmington and then ship to Brimhaven.

**Comment by Skretzo** [comment]
Based on the available transports in the plugin this is actually the shortest path. The black areas are confusing, but they are black because the in-game world map does not work too well for dungeons, instances and similar areas that have coordinates really far away from the main map. Try following map links (![dungeon_map_link](https://user-images.githubusercontent.com/53493631/208209264-234013ee-6d55-40aa-91e9-a438a60c4f99.png) ![map_link](https://user-images.githubusercontent.com/53493631/208209635-549ee423-98f9-4fe3-8b69-2fe318c406a6.png)) in the map if they are available instead of panning out of the main map.

The first black area it takes you to is the city of Mor Ul Rek:
![mor_ul_rek](https://user-images.githubusercontent.com/53493631/208208956-62d5673e-5c14-4e9d-b591-5607e60786db.png)

The second black area it takes you to is the Karamja Dungeon:
![karamja_dungeon](https://user-images.githubusercontent.com/53493631/208209061-69dc4ac7-06d8-4c1a-bd90-8a8b40fbdf20.png)
