### ISSUE TITLE
Minimap right click option to clear the current path conflicts with the zoom functionality in the Minimap plugin.

### ISSUE THREAD

**Issue by Excyrial** [Skretzo/shortest-path#22]
Mostly a fyi i suppose:

In the 1.9.0 version of Runelite the standard minimap plugin now support a "Zoom" feature for the minimap. If this feature is used, it will cause a right mouse click on the minimap to reset the map to the default zoom level.

This seems to conflict with the shortest path plugin, as it uses a right click on the minimap to display a context menu allowing the user to reset the current path. (This is still possible from the full world map though).

**Comment by Skretzo** [comment]
A workaround to this problem was released in [version 1.9.3](https://github.com/Skretzo/shortest-path/compare/4e75fb99542619106cc01da14bdaa5ad1c64e7fa...Skretzo:b57d79bfc2ded948195b68d645bd26024fe5d817) which involves an additional right-click `Clear Path` option on the minimap world map icon button. Restart your client to fetch the update.
![clear-path-world-map-globe](https://user-images.githubusercontent.com/53493631/211226420-6f92518b-0047-4074-b568-be078983d781.png)
