### ISSUE TITLE
Suggestion: Add spirit trees and or gnome gliders

### ISSUE THREAD

**Issue by Fjara-h** [Skretzo/shortest-path#29]
Would be nice to include these if the performance hit isn't too much - I am currently on early-ish game ironman effectively just questing and my primary transport is fairy rings (already included), spirit trees, and gliders as I mainly use the Ardy cloak 1. I don't know how much use the gliders would get but the tree is pretty essential for me.

Thanks Skretzo!

**Comment by Skretzo** [comment]
I am actually working on adding gnome gliders, so it will be in the next release.
If you want to help out I need the number of ticks it takes to travel to each destination

**Comment by Fjara-h** [comment]
https://www.youtube.com/watch?v=TSSr9Kn8MBg

is this sufficient? i do not have access to ape atoll

**Comment by Skretzo** [comment]
I can work with that, sure, but a tick counter on the report button instead of login time would be easier

**Comment by Fjara-h** [comment]
Here is a 2nd with the tick counter https://www.youtube.com/watch?v=yDRAWOJX_AE

**Comment by Oliver-Saer** [comment]
Any updates on this, is it still planned for future release?

**Comment by Skretzo** [comment]
This is definitely still a planned feature, but I sadly do not have an ETA. Here's why:

Spirit trees are big objects that allow you to interact with the tree at different locations and teleport you from there:
![gnome_stronghold_spirit_tree](https://github.com/Skretzo/shortest-path/assets/53493631/be8c4a82-ca62-4626-a3ef-9fe5679eb7ed)
_The Tree Gnome Stronghold spirit tree in red, with the blue pins indicating possible transport starting locations_

When you have several possible transport end locations, this actually adds up to quite a lot of possible transport combinations for each spirit tree:

|Spirit tree|Possible transport start locations|Possible combinations of transports (*)|
|:----------:|:-----------------------------------:|:-----------------------------------------:|
|Tree Gnome Village|15|15 * 5 = 75|
|Tree Gnome Stronghold|14|14 * 5 = 70|
|Battlefield of Khazard|8|8 * 5 = 40|
|Grand Exchange|8|8 * 5 = 40|
|Feldip hills|8|8 * 5 = 40|
|Prifddinas|7|7 * 5 = 35|

_(*) This is only for the 5 permanent spirit trees, and will be bigger if the PoH and self-grown spirit trees are included_

A conservative total number of transport combinations for spirit trees is therefore 300. The plugin already has around 6000 transports.

Why am I even bringing this up?

It turns out that for every single transport I add to the plugin, the plugin gets a little bit slower...
I guess you could call it a bug, but it is sadly not easy to fix. It has to do with having standard pathfinding where each movement is connected tile-by-tile and combining this with the option to jump big distances (e.g. spirit tree) in the transportation network. Long story short is that I have to rewrite the entire plugin, and even then I am not sure if it is even possible to design a system that can support this properly (e.g. I don't have a server like Google Maps and cannot precompute likely good/frequently used paths).

In addition I have not really had the time to work on this. Maybe during the summer?

**Comment by Oliver-Saer** [comment]
Thanks for the really detailed explanation, it's a privilege to get some insight into your process.

Just two _off-the-cuff_ suggestions for you (from a position of ignorance, so take them with a pinch of salt):
- Maybe release it according to your current design with as an opt-in beta feature, with a disclaimer regarding the performance hit (assuming it's possible to skip this logic and retain performance if the feature is toggled off).
- Would it be possible to set the navigation endpoint to a occupied by the Spirit Tree (thereby making it one transport start location per Spirit Tree), then work backwards removing tiles which would be inaccessible by the player?  That way at least they're in the vicinity of the Spirit Tree, despite not being navigated directly to the optimal tile.
	- I acknowledge this goes against the spirit of the plugin somewhat, that being to find the shortest path, but this could again be prefaced by a disclaimer.

**Comment by Skretzo** [comment]
> as an opt-in beta feature

They will be opt-in, and I will reorganize the already available transports into more opt-in options. Opting out will retain previous performance.

> Would it be possible to set the navigation endpoint to a tile occupied by the Spirit Tree

The endpoint is not the problem as it is usually only a single tile, it is the starting point that is the problem. Yes, it is possible to set the centre of the spirit tree as the starting point and from the object on that tile determine where the edge of the spirit tree is. However, this does not really help us because we are searching for starting points differently. When we are pathfinding we pick a single tile at a time and ask "Are any of the nearby 8 tiles walkable or a transport starting point?" What we need is a better way to figure out if a specific tile has a transport other than going through every roughly 6000 transports and checking if there is a match.

**Comment by Skretzo** [comment]
Thanks to major performance improvements by @jocopa3, this plugin is now much faster and uses less memory. This is very good news for adding more transports, such as spirit trees and gnome gliders!

Gnome gliders have now been added to the plugin in version 1.10 as a separate option `Use gnome gliders`, and is already live in the client.

Spirit trees will hopefully be added to the plugin in the next version.

**Comment by Skretzo** [comment]
Spirit trees were added to the plugin in version 1.11 and is now live in the client.
