### ISSUE TITLE
pathing is completelyy broken and will not automaticly make your carecter move due to the new old school runescape update that cam out a week ago

### ISSUE THREAD

**Issue by btl200** [Skretzo/shortest-path#34]
When i right-click and do set a target it doesn't automaticly move my person to the right-clicked mini map location

**Comment by Skretzo** [comment]
Can you provide an image of what is broken?

Right-clicking and setting a target has never automatically moved the player, that only happens when you left-click `Walk here` or left-click on the minimap. It is not possible to move the player by clicking on the world map.

What do you mean by right-clicked mini map location? The only option on the minimap is `Clear Path` when you have an active path, and this does not move the player.
